DROP TABLE IF EXISTS CUENTAS;
CREATE TABLE CUENTAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NROCUENTA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
SALDO DOUBLE NOT NULL);

INSERT INTO CUENTAS
VALUES (1, 123424, "AHORROS", 200000);

